import type { LiveCertificateMetadata } from '../types'

const STORAGE_KEY = 'atlas-demo-live-certificates-v1'
const endpoint = (import.meta.env.VITE_DEMO_INSPECTION_URL as string | undefined) ?? '/api/demo-certificates'
interface DemoInspectionResponse { items: LiveCertificateMetadata[]; inspectedAt: string }

function validItem(value: unknown): value is LiveCertificateMetadata { if (!value || typeof value !== 'object') return false; const item = value as Record<string, unknown>; return typeof item.hostname === 'string' && item.port === 443 && typeof item.expiresAt === 'string' && typeof item.inspectedAt === 'string' }
export function readCachedDemoCertificates(): { items: LiveCertificateMetadata[]; refreshedAt: string } | null { try { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return null; const parsed = JSON.parse(raw) as Partial<DemoInspectionResponse>; if (!Array.isArray(parsed.items) || !parsed.items.every(validItem) || typeof parsed.inspectedAt !== 'string') return null; return { items: parsed.items, refreshedAt: parsed.inspectedAt } } catch { return null } }
export async function fetchDemoCertificates(force = false): Promise<{ items: LiveCertificateMetadata[]; refreshedAt: string }> { const response = await fetch(`${endpoint}${endpoint.includes('?') ? '&' : '?'}refresh=${force ? '1' : '0'}`, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error(response.status === 429 ? 'Refresh limit reached. Try again in a minute.' : 'Live certificate inspection is temporarily unavailable.'); let payload: Partial<DemoInspectionResponse>; try { payload = await response.json() as Partial<DemoInspectionResponse> } catch { throw new Error('Live certificate inspection is temporarily unavailable.') } if (!Array.isArray(payload.items) || !payload.items.every(validItem) || !payload.items.length || typeof payload.inspectedAt !== 'string') throw new Error('Live inspection returned an invalid response.'); const value = { items: payload.items, refreshedAt: payload.inspectedAt }; try { localStorage.setItem(STORAGE_KEY, JSON.stringify({ items: value.items, inspectedAt: value.refreshedAt })) } catch { /* Browser storage is optional. */ } return value }
