import type { SupabaseClient } from '@supabase/supabase-js'
import type { AtlasData, AuditEvent, Certificate, Customer, Deployment, Environment, Notification, RenewalTask, RenewalWorkflow, Runbook, ValidationCheck } from '../types'

type Row = Record<string, unknown>
const text = (value: unknown, fallback = '') => typeof value === 'string' ? value : fallback
const list = (value: unknown) => Array.isArray(value) ? value.map(String) : []
const title = (value: unknown) => text(value).split('_').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ')
const rows = (value: unknown) => (Array.isArray(value) ? value : []) as Row[]

export class SupabaseDataRepository {
  constructor(private readonly client: SupabaseClient, private readonly organizationId: string, private readonly actorId: string) {}

  async load(): Promise<AtlasData> {
    const tables = ['customers', 'environments', 'certificates', 'certificate_deployments', 'renewal_workflows', 'renewal_tasks', 'runbooks', 'validation_checks', 'audit_events', 'notifications'] as const
    const results = await Promise.all(tables.map((table) => this.client.from(table).select('*').eq('organization_id', this.organizationId)))
    const failure = results.find((result) => result.error)?.error
    if (failure) throw new Error(`Unable to load production workspace: ${failure.message}`)
    const [customerRows, environmentRows, certificateRows, deploymentRows, workflowRows, taskRows, runbookRows, validationRows, auditRows, notificationRows] = results.map((result) => rows(result.data))
    const environments: Environment[] = environmentRows.map((row) => ({ id: text(row.id), customerId: text(row.customer_id), name: text(row.name), kind: text(row.kind, 'custom') }))
    const customers: Customer[] = customerRows.map((row) => ({ id: text(row.id), name: text(row.name), slug: text(row.slug), industry: text(row.industry), environments: environments.filter((environment) => environment.customerId === row.id).map((environment) => environment.name) }))
    const certificates: Certificate[] = certificateRows.map((row) => ({ id: text(row.id), customerId: text(row.customer_id), environment: environments.find((environment) => environment.id === row.environment_id)?.name ?? 'Unassigned', commonName: text(row.common_name), sanNames: list(row.san_names), serialNumber: text(row.serial_number), issuer: text(row.issuer), certificateAuthority: text(row.certificate_authority), notBefore: text(row.not_before, text(row.created_at)), expiresAt: text(row.expires_at), fingerprint: text(row.fingerprint), renewalMethod: text(row.renewal_method, 'Manual'), owner: text(row.owner_team, row.owner_user_id ? 'Assigned user' : 'Unassigned'), ownerTeam: text(row.owner_team), notes: text(row.notes), statusOverride: row.status_override ? title(row.status_override) as Certificate['statusOverride'] : undefined }))
    const deployments: Deployment[] = deploymentRows.map((row) => ({ id: text(row.id), certificateId: text(row.certificate_id), name: text(row.name), type: text(row.target_type), hostname: text(row.hostname_or_reference), environment: environments.find((environment) => environment.id === row.environment_id)?.name ?? 'Unassigned', method: title(row.deployment_method) as Deployment['method'], owner: text(row.owner_team, row.owner_user_id ? 'Assigned user' : 'Unassigned'), vendor: text(row.vendor) || undefined, vendorContact: text(row.vendor_contact) || undefined, maintenanceWindow: text(row.maintenance_window), automationStatus: text(row.automation_status), validationMethod: text(row.validation_method), lastDeployment: text(row.last_deployment_at) || undefined, lastValidation: text(row.last_validation_at) || undefined, status: title(row.status) as Deployment['status'], dependencies: list(row.dependencies), runbookId: text(row.runbook_id) || undefined }))
    const workflows: RenewalWorkflow[] = workflowRows.map((row) => ({ id: text(row.id), certificateId: text(row.certificate_id), status: title(row.status) as RenewalWorkflow['status'], startedAt: text(row.started_at, text(row.created_at)), dueDate: text(row.due_date, text(row.created_at)), owner: row.owner_user_id ? 'Assigned user' : 'Unassigned', taskIds: taskRows.filter((task) => task.workflow_id === row.id).map((task) => text(task.id)) }))
    const tasks: RenewalTask[] = taskRows.map((row) => ({ id: text(row.id), workflowId: text(row.workflow_id), deploymentId: text(row.deployment_id) || undefined, title: text(row.title), type: title(row.task_type) as RenewalTask['type'], owner: row.owner_user_id ? 'Assigned user' : 'Unassigned', status: title(row.status) as RenewalTask['status'], method: title(row.method) as RenewalTask['method'], instructions: text(row.instructions), dependencies: list(row.dependency_task_ids), dueDate: text(row.due_date, text(row.created_at)), completedAt: text(row.completed_at) || undefined, validationResult: row.validation_result ? title(row.validation_result) as RenewalTask['validationResult'] : undefined, vendor: text(row.vendor) || undefined, ticketNumber: text(row.ticket_number) || undefined }))
    const runbooks: Runbook[] = runbookRows.map((row) => ({ id: text(row.id), deploymentId: deployments.find((deployment) => deployment.runbookId === row.id)?.id ?? '', title: text(row.title), description: text(row.description), steps: list(row.steps), warnings: list(row.warnings), expectedValidation: text(row.expected_validation) }))
    const validations: ValidationCheck[] = validationRows.map((row) => ({ id: text(row.id), certificateId: text(row.certificate_id), deploymentId: text(row.deployment_id), type: text(row.check_type) === 'manual' ? 'Manual' : 'Automatic TLS', expected: JSON.stringify(row.expected_result ?? {}), actual: JSON.stringify(row.actual_result ?? {}), checkedAt: text(row.checked_at), success: Boolean(row.success) }))
    const auditEvents: AuditEvent[] = auditRows.sort((a, b) => text(b.occurred_at).localeCompare(text(a.occurred_at))).map((row) => ({ id: text(row.id), action: text(row.action), entityType: text(row.entity_type), entityId: text(row.entity_id), actor: row.actor_user_id === this.actorId ? 'You' : 'Organization member', timestamp: text(row.occurred_at), metadata: typeof row.metadata === 'object' ? JSON.stringify(row.metadata) : text(row.metadata) }))
    const notifications: Notification[] = notificationRows.sort((a, b) => text(b.created_at).localeCompare(text(a.created_at))).map((row) => ({ id: text(row.id), title: text(row.title), message: text(row.message), severity: text(row.severity, 'info') as Notification['severity'], read: Boolean(row.read_at), createdAt: text(row.created_at) }))
    return { customers, environments, certificates, deployments, workflows, tasks, runbooks, validations, auditEvents, notifications }
  }

  private async audit(action: string, entityType: string, entityId: string, metadata: Row) { const { error } = await this.client.from('audit_events').insert({ organization_id: this.organizationId, actor_user_id: this.actorId, action, entity_type: entityType, entity_id: entityId, metadata }); if (error) throw error }
  async createCustomer(input: { name: string; industry: string }): Promise<void> { const slug = `${input.name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}-${crypto.randomUUID().slice(0, 6)}`; const { data, error } = await this.client.from('customers').insert({ organization_id: this.organizationId, name: input.name, industry: input.industry, slug }).select('id').single(); if (error) throw error; await this.audit('customer.created', 'customer', data.id, { name: input.name }) }
  async createEnvironment(input: { customerId: string; name: string; kind: string }): Promise<void> { const { data, error } = await this.client.from('environments').insert({ organization_id: this.organizationId, customer_id: input.customerId, name: input.name, kind: input.kind }).select('id').single(); if (error) throw error; await this.audit('environment.created', 'environment', data.id, { name: input.name }) }
  async createCertificate(certificate: Certificate): Promise<void> { const environment = await this.client.from('environments').select('id').eq('organization_id', this.organizationId).eq('customer_id', certificate.customerId).eq('name', certificate.environment).maybeSingle(); if (environment.error) throw environment.error; const { data, error } = await this.client.from('certificates').insert({ organization_id: this.organizationId, customer_id: certificate.customerId, environment_id: environment.data?.id ?? null, common_name: certificate.commonName, san_names: certificate.sanNames, serial_number: certificate.serialNumber, issuer: certificate.issuer, certificate_authority: certificate.certificateAuthority, not_before: certificate.notBefore, expires_at: certificate.expiresAt, fingerprint: certificate.fingerprint, renewal_method: certificate.renewalMethod, owner_team: certificate.ownerTeam, notes: certificate.notes }).select('id').single(); if (error) throw error; await this.audit('certificate.created', 'certificate', data.id, { common_name: certificate.commonName }) }
  async createDeployment(input: { certificateId: string; name: string; type: string; hostname: string; method: string; vendor: string; maintenanceWindow: string; validationMethod: string }): Promise<void> { const certificate = await this.client.from('certificates').select('customer_id,environment_id').eq('organization_id', this.organizationId).eq('id', input.certificateId).single(); if (certificate.error) throw certificate.error; const { data, error } = await this.client.from('certificate_deployments').insert({ organization_id: this.organizationId, certificate_id: input.certificateId, customer_id: certificate.data.customer_id, environment_id: certificate.data.environment_id, name: input.name, target_type: input.type, hostname_or_reference: input.hostname, deployment_method: input.method, owner_user_id: this.actorId, vendor: input.vendor || null, maintenance_window: input.maintenanceWindow, automation_status: input.method === 'automated' ? 'Automated' : 'Manual coordination', validation_method: input.validationMethod, status: 'pending' }).select('id').single(); if (error) throw error; await this.audit('deployment.created', 'certificate_deployment', data.id, { name: input.name }) }
  async createRunbook(input: { deploymentId: string; title: string; description: string; steps: string[]; warnings: string[]; expectedValidation: string }): Promise<void> { const { data, error } = await this.client.from('runbooks').insert({ organization_id: this.organizationId, title: input.title, description: input.description, steps: input.steps, warnings: input.warnings, expected_validation: input.expectedValidation }).select('id').single(); if (error) throw error; const link = await this.client.from('certificate_deployments').update({ runbook_id: data.id }).eq('organization_id', this.organizationId).eq('id', input.deploymentId); if (link.error) throw link.error; await this.audit('runbook.created', 'runbook', data.id, { title: input.title }) }
  async updateCertificate(id: string, changes: Partial<Certificate>): Promise<void> { const payload: Row = {}; if (changes.commonName !== undefined) payload.common_name = changes.commonName; if (changes.sanNames !== undefined) payload.san_names = changes.sanNames; if (changes.expiresAt !== undefined) payload.expires_at = changes.expiresAt; if (changes.issuer !== undefined) payload.issuer = changes.issuer; if (changes.notes !== undefined) payload.notes = changes.notes; const { error } = await this.client.from('certificates').update(payload).eq('organization_id', this.organizationId).eq('id', id); if (error) throw error; await this.audit('certificate.updated', 'certificate', id, { fields: Object.keys(payload) }) }
  async deleteRecord(table: 'customers' | 'environments' | 'certificates' | 'certificate_deployments' | 'runbooks' | 'integration_configs', id: string): Promise<void> { const { error } = await this.client.from(table).delete().eq('organization_id', this.organizationId).eq('id', id); if (error) throw error; await this.audit(`${table}.deleted`, table, id, {}) }
  async completeTask(id: string): Promise<void> { const current = await this.client.from('renewal_tasks').select('task_type,deployment_id,workflow_id,title').eq('organization_id', this.organizationId).eq('id', id).single(); if (current.error) throw current.error; const payload: Row = { status: 'completed', completed_at: new Date().toISOString() }; if (current.data.task_type === 'validation') { payload.validation_result = 'passed'; const workflow = await this.client.from('renewal_workflows').select('certificate_id').eq('organization_id', this.organizationId).eq('id', current.data.workflow_id).single(); if (workflow.error) throw workflow.error; const validation = await this.client.from('validation_checks').insert({ organization_id: this.organizationId, certificate_id: workflow.data.certificate_id, deployment_id: current.data.deployment_id, check_type: 'manual', expected_result: { outcome: 'renewed certificate presented' }, actual_result: { outcome: 'operator confirmed success' }, success: true }); if (validation.error) throw validation.error }
    const { error } = await this.client.from('renewal_tasks').update(payload).eq('organization_id', this.organizationId).eq('id', id); if (error) throw error; await this.audit('task.completed', 'renewal_task', id, { title: current.data.title }); const completion = await this.client.rpc('complete_renewal', { target_workflow: current.data.workflow_id }); if (completion.error) throw completion.error }
  async retryTask(id: string): Promise<void> { const { error } = await this.client.from('renewal_tasks').update({ status: 'in_progress', validation_result: null }).eq('organization_id', this.organizationId).eq('id', id); if (error) throw error; await this.audit('task.retried', 'renewal_task', id, {}) }
  async markNotificationsRead(): Promise<void> { const { error } = await this.client.from('notifications').update({ read_at: new Date().toISOString() }).eq('organization_id', this.organizationId).is('read_at', null); if (error) throw error }
  async startRenewal(certificateId: string): Promise<void> { const { error } = await this.client.rpc('start_renewal', { target_certificate: certificateId }); if (error) throw error }
}
