import { ArrowLeft, Check, CircleAlert, Clock3, ExternalLink, RotateCw, Server, ShieldCheck, User } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { certificateStatus, daysUntil, formatDate, progressForTasks } from '../lib/domain'
import { useAppPath } from '../lib/routes'

export function CertificateDetail() {
  const { id } = useParams(); const data = useData(); const { path } = useAppPath(); const cert = data.certificates.find((c) => c.id === id)
  if (!cert) return <div className="empty-state"><h2>Certificate not found</h2><Link to={path('/certificates')}>Return to inventory</Link></div>
  const customer = data.customers.find((c) => c.id === cert.customerId); const deployments = data.deployments.filter((d) => d.certificateId === cert.id); const workflow = data.workflows.find((w) => w.certificateId === cert.id); const tasks = data.tasks.filter((t) => t.workflowId === workflow?.id); const validations = data.validations.filter((v) => v.certificateId === cert.id); const events = data.auditEvents.filter((e) => e.entityId === cert.id || tasks.some((t) => t.id === e.entityId) || deployments.some((d) => d.id === e.entityId))
  return <><Link to={path('/certificates')} className="back-link"><ArrowLeft size={15} /> Certificate inventory</Link><PageHeader eyebrow={`${customer?.name} / ${cert.environment}`} title={cert.commonName} description={`${cert.certificateAuthority} · ${cert.sanNames.length} subject alternative names`} actions={<><button className="button secondary" onClick={() => void data.startRenewal(cert.id)} disabled={Boolean(workflow)}><RotateCw size={15} /> {workflow ? 'Renewal active' : 'Start renewal'}</button><button className="button primary">Edit metadata</button></>} />
    <section className="cert-hero"><div><StatusBadge>{certificateStatus(cert)}</StatusBadge><h2>{daysUntil(cert.expiresAt)} days remaining</h2><p>Expires {formatDate(cert.expiresAt)}</p><div className="expiry-track"><i style={{ width: `${Math.max(2, Math.min(100, daysUntil(cert.expiresAt) / 3.65))}%` }} /></div></div><div className="hero-stat"><User /><span>Operational owner<strong>{cert.owner}</strong><small>{cert.ownerTeam}</small></span></div><div className="hero-stat"><Server /><span>Deployment targets<strong>{deployments.length} systems</strong><small>{deployments.filter((d) => d.status !== 'Completed').length} need action</small></span></div><div className="hero-stat"><ShieldCheck /><span>Last validation<strong>{validations[0] ? formatDate(validations[0].checkedAt) : 'Not validated'}</strong><small>{validations[0]?.success ? 'Passed' : validations[0] ? 'Failed' : 'No checks recorded'}</small></span></div></section>
    <div className="detail-grid"><section className="panel span-2"><div className="panel-heading"><div><h2>Deployment targets</h2><p>Every known location where this certificate is used</p></div><Link to={path('/deployments')}>Manage targets</Link></div>{deployments.map((dep) => <div className="deployment-row" key={dep.id}><div className="system-icon"><Server size={18} /></div><div className="grow"><strong>{dep.name}</strong><span>{dep.type} · {dep.hostname}</span><small>{dep.dependencies.length ? `Depends on: ${dep.dependencies.join(', ')}` : 'No external dependencies'}</small></div><div><span className="label">Method</span><strong>{dep.method}</strong></div><div><span className="label">Owner</span><strong>{dep.owner}</strong></div><StatusBadge>{dep.status}</StatusBadge></div>)}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Certificate metadata</h2><p>Non-secret X.509 information</p></div></div><dl className="metadata"><dt>Common name</dt><dd>{cert.commonName}</dd><dt>Issuer</dt><dd>{cert.issuer}</dd><dt>Serial number</dt><dd className="mono">{cert.serialNumber}</dd><dt>Fingerprint</dt><dd className="mono">{cert.fingerprint}</dd><dt>Valid from</dt><dd>{formatDate(cert.notBefore)}</dd><dt>Renewal method</dt><dd>{cert.renewalMethod}</dd></dl></section>
      {workflow && <section className="panel span-2"><div className="panel-heading"><div><h2>Renewal workflow</h2><p>Renewal is complete only after every required validation passes</p></div><StatusBadge>{workflow.status}</StatusBadge></div><div className="workflow-summary"><div><strong>{progressForTasks(tasks)}%</strong><span>deployment completion</span></div><div className="progress"><i style={{ width: `${progressForTasks(tasks)}%` }} /></div><span>Due {formatDate(workflow.dueDate)}</span></div><div className="task-list">{tasks.map((task) => <div className="task-row" key={task.id}><span className={`task-check ${task.status === 'Completed' ? 'done' : task.status === 'Failed' ? 'failed' : ''}`}>{task.status === 'Completed' ? <Check size={14} /> : task.status === 'Failed' ? <CircleAlert size={14} /> : <Clock3 size={14} />}</span><div className="grow"><strong>{task.title}</strong><span>{task.type} · {task.method} · {task.owner}</span>{task.vendor && <small>{task.vendor} · Ticket {task.ticketNumber}</small>}</div><StatusBadge>{task.status}</StatusBadge>{task.status !== 'Completed' && task.status !== 'Blocked' && <button className="button tiny" onClick={() => data.completeTask(task.id)}>Mark complete</button>}</div>)}</div></section>}
      <section className="panel"><div className="panel-heading"><div><h2>Runbook</h2><p>Target-specific operating procedures</p></div></div>{data.runbooks.filter((runbook) => deployments.some((d) => d.id === runbook.deploymentId)).slice(0, 2).map((runbook) => <Link to={path('/runbooks')} className="runbook-link" key={runbook.id}><div><strong>{runbook.title}</strong><span>{runbook.steps.length} ordered steps</span></div><ExternalLink size={15} /></Link>)}</section>
      <section className="panel span-2"><div className="panel-heading"><div><h2>Validation</h2><p>Expected and observed deployment state</p></div></div>{validations.length ? validations.map((validation) => <div className="validation-row" key={validation.id}><div className={validation.success ? 'validation-icon success' : 'validation-icon failure'}>{validation.success ? <Check size={17} /> : <CircleAlert size={17} />}</div><div className="grow"><strong>{validation.type} · {validation.success ? 'Passed' : 'Failed'}</strong><span>Expected: {validation.expected}</span><small>Actual: {validation.actual}</small></div><time>{formatDate(validation.checkedAt)}</time></div>) : <p className="muted">No validation checks have been recorded.</p>}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Activity</h2><p>Append-oriented audit history</p></div></div>{events.length ? events.map((event) => <div className="mini-event" key={event.id}><span /><div><strong>{event.action.replaceAll('.', ' ')}</strong><p>{event.metadata}</p><small>{event.actor} · {formatDate(event.timestamp)}</small></div></div>) : <p className="muted">No activity recorded.</p>}</section>
    </div></>
}
