import { ChevronDown, ListFilter, Plus, Search } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { EmptyState } from '../components/EmptyState'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { certificateStatus, daysUntil, formatDate } from '../lib/domain'
import { useAppPath } from '../lib/routes'
import type { Certificate } from '../types'

export function Certificates() {
  const data = useData(); const { path } = useAppPath(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All statuses'); const [customer, setCustomer] = useState('All customers'); const [showAdd, setShowAdd] = useState(false)
  const items = useMemo(() => data.certificates.filter((cert) => (cert.commonName.toLowerCase().includes(query.toLowerCase()) || cert.sanNames.some((san) => san.includes(query.toLowerCase()))) && (status === 'All statuses' || certificateStatus(cert) === status) && (customer === 'All customers' || cert.customerId === customer)).sort((a, b) => daysUntil(a.expiresAt) - daysUntil(b.expiresAt)), [data.certificates, query, status, customer])
  return <><PageHeader eyebrow="Certificate operations" title="Certificate inventory" description={`${data.certificates.length} certificates monitored across ${data.customers.length} customers.`} actions={<button className="button primary" onClick={() => setShowAdd(true)} disabled={data.customers.length === 0}><Plus size={16} /> Add certificate</button>} />
    <div className="toolbar"><label className="search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search common name or SAN…" /></label><label className="select"><ListFilter size={16} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option>All statuses</option>{['Healthy', 'Expiring Soon', 'Critical', 'Expired', 'Renewal In Progress', 'Validation Failed'].map((item) => <option key={item}>{item}</option>)}</select><ChevronDown size={14} /></label><label className="select"><select value={customer} onChange={(event) => setCustomer(event.target.value)}><option>All customers</option>{data.customers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><ChevronDown size={14} /></label><span className="result-count">{items.length} results</span></div>
    {items.length === 0 ? <EmptyState title="No certificates monitored" description={data.certificates.length === 0 ? 'Add a customer and certificate metadata to begin monitoring the estate.' : 'No certificates match the current search and filters.'} /> : <div className="table-card"><div className="data-table cert-table"><div className="table-head"><span>Certificate</span><span>Customer / environment</span><span>Issuer</span><span>Expiration</span><span>Owner</span><span>Targets</span><span>Status</span></div>{items.map((cert) => <Link className="table-row" to={path(`/certificates/${cert.id}`)} key={cert.id}><span className="primary-cell"><strong>{cert.commonName}</strong><small>{cert.sanNames.length} SAN{cert.sanNames.length === 1 ? '' : 's'} · {cert.renewalMethod}</small></span><span><strong>{data.customers.find((item) => item.id === cert.customerId)?.name}</strong><small>{cert.environment}</small></span><span><strong>{cert.certificateAuthority}</strong><small>{cert.issuer.slice(0, 30)}</small></span><span><strong className={daysUntil(cert.expiresAt) <= 7 ? 'text-danger' : ''}>{daysUntil(cert.expiresAt)} days</strong><small>{formatDate(cert.expiresAt)}</small></span><span><strong>{cert.owner}</strong><small>{cert.ownerTeam}</small></span><span><strong>{data.deployments.filter((deployment) => deployment.certificateId === cert.id).length}</strong></span><span><StatusBadge>{certificateStatus(cert)}</StatusBadge></span></Link>)}</div></div>}
    {showAdd && <AddCertificate onClose={() => setShowAdd(false)} />}</>
}

function AddCertificate({ onClose }: { onClose(): void }) {
  const data = useData(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [customerId, setCustomerId] = useState(data.customers[0]?.id ?? '')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const expiresAt = new Date(String(form.get('expiresAt'))); if (Number.isNaN(expiresAt.getTime())) { setError('Enter a valid expiration date.'); return } const certificate: Certificate = { id: crypto.randomUUID(), customerId, environment: String(form.get('environment')), commonName: String(form.get('commonName')).trim(), sanNames: String(form.get('sans')).split(',').map((value) => value.trim()).filter(Boolean), serialNumber: String(form.get('serial')), issuer: String(form.get('issuer')), certificateAuthority: String(form.get('authority')), notBefore: new Date().toISOString(), expiresAt: expiresAt.toISOString(), fingerprint: String(form.get('fingerprint')), renewalMethod: String(form.get('renewalMethod')), owner: 'Current user', ownerTeam: String(form.get('ownerTeam')), notes: String(form.get('notes')) }; if (!certificate.commonName || !certificate.customerId) { setError('Common name and customer are required.'); return } setBusy(true); setError(''); try { await data.addCertificate(certificate); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to add certificate.') } finally { setBusy(false) } }
  const environments = data.environments.filter((environment) => environment.customerId === customerId)
  return <Modal title="Add certificate metadata" onClose={onClose}><form className="form-grid" onSubmit={submit}><div className="form-note">Atlas stores certificate metadata only. Never paste or upload private key material.</div><label className="full">Common name<input name="commonName" required placeholder="api.example.com" /></label><label>Customer<select name="customerId" value={customerId} onChange={(event) => setCustomerId(event.target.value)} required>{data.customers.map((customer) => <option value={customer.id} key={customer.id}>{customer.name}</option>)}</select></label><label>Environment<select name="environment" required>{environments.length ? environments.map((environment) => <option key={environment.id}>{environment.name}</option>) : <option>Unassigned</option>}</select></label><label className="full">Subject alternative names<input name="sans" placeholder="api.example.com, www.example.com" /></label><label>Issuer<input name="issuer" required placeholder="DigiCert…" /></label><label>Certificate authority<input name="authority" required placeholder="DigiCert" /></label><label>Expiration date<input name="expiresAt" type="datetime-local" required /></label><label>Renewal method<input name="renewalMethod" required defaultValue="Manual" /></label><label>Owner team<input name="ownerTeam" defaultValue="Certificate Operations" /></label><label>Serial number<input name="serial" /></label><label className="full">Fingerprint<input name="fingerprint" /></label><label className="full">Notes<textarea name="notes" rows={3} /></label>{error && <p className="form-error full">{error}</p>}<div className="form-actions full"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Adding…' : 'Add metadata'}</button></div></form></Modal>
}
