import { ArrowLeft, Check, CircleAlert, Clock3, ExternalLink, RotateCw, Server, ShieldCheck, User } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useState, type FormEvent } from 'react'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { WorkflowTimeline } from '../components/WorkflowTimeline'
import { useData } from '../context/DataContext'
import { certificateStatus, daysUntil, formatDate, progressForTasks } from '../lib/domain'
import { useAppPath } from '../lib/routes'

export function CertificateDetail() {
  const { id } = useParams(); const data = useData(); const { path } = useAppPath(); const [editing, setEditing] = useState(false); const [actionError, setActionError] = useState(''); const cert = data.certificates.find((c) => c.id === id)
  if (!cert) return <div className="empty-state"><h2>Certificate not found</h2><Link to={path('/certificates')}>Return to inventory</Link></div>
  const customer = data.customers.find((c) => c.id === cert.customerId); const deployments = data.deployments.filter((d) => d.certificateId === cert.id); const certificateWorkflows = data.workflows.filter((w) => w.certificateId === cert.id); const activeWorkflow = certificateWorkflows.find((w) => !['Completed', 'Failed'].includes(w.status)); const workflow = activeWorkflow ?? [...certificateWorkflows].sort((a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime())[0]; const tasks = data.tasks.filter((t) => t.workflowId === workflow?.id); const validations = data.validations.filter((v) => v.certificateId === cert.id); const events = data.auditEvents.filter((e) => e.entityId === cert.id || tasks.some((t) => t.id === e.entityId) || deployments.some((d) => d.id === e.entityId))
  return <><Link to={path('/certificates')} className="back-link"><ArrowLeft size={15} /> Certificate inventory</Link><PageHeader eyebrow={`${customer?.name} / ${cert.environment}`} title={cert.commonName} description={`${cert.certificateAuthority} · ${cert.sanNames.length} subject alternative names`} actions={<><button className="button secondary" onClick={async () => { setActionError(''); try { await data.startRenewal(cert.id) } catch (cause) { setActionError(cause instanceof Error ? cause.message : 'Unable to start renewal.') } }} disabled={Boolean(activeWorkflow) || deployments.length === 0} title={activeWorkflow ? 'This certificate already has an active renewal.' : deployments.length === 0 ? 'Add a deployment target before starting a renewal.' : undefined}><RotateCw size={15} /> {activeWorkflow ? 'Renewal active' : 'Start renewal'}</button><button className="button primary" onClick={() => setEditing(true)}>Edit metadata</button></>} />{actionError && <div className="workspace-error compact" role="alert">{actionError}</div>}
    <section className="cert-hero"><div><StatusBadge>{certificateStatus(cert)}</StatusBadge><h2>{daysUntil(cert.expiresAt)} days remaining</h2><p>Expires {formatDate(cert.expiresAt)}</p><div className="expiry-track"><i style={{ width: `${Math.max(2, Math.min(100, daysUntil(cert.expiresAt) / 3.65))}%` }} /></div></div><div className="hero-stat"><User /><span>Operational owner<strong>{cert.owner}</strong><small>{cert.ownerTeam}</small></span></div><div className="hero-stat"><Server /><span>Deployment targets<strong>{deployments.length} systems</strong><small>{deployments.filter((d) => d.status !== 'Completed').length} need action</small></span></div><div className="hero-stat"><ShieldCheck /><span>Last validation<strong>{validations[0] ? formatDate(validations[0].checkedAt) : 'Not validated'}</strong><small>{validations[0]?.success ? 'Passed' : validations[0] ? 'Failed' : 'No checks recorded'}</small></span></div></section>
    <div className="detail-grid"><section className="panel span-2"><div className="panel-heading"><div><h2>Deployment targets</h2><p>Every known location where this certificate is used</p></div><Link to={path('/deployments')}>Manage targets</Link></div>{deployments.map((dep) => <Link className="deployment-row" to={path(`/deployments/${dep.id}`)} key={dep.id}><div className="system-icon"><Server size={18} /></div><div className="grow"><strong>{dep.name}</strong><span>{dep.type} · {dep.hostname}</span><small>{dep.dependencies.length ? `Depends on: ${dep.dependencies.join(', ')}` : 'No external dependencies'}</small></div><div><span className="label">Method</span><strong>{dep.method}</strong></div><div><span className="label">Owner</span><strong>{dep.owner}</strong></div><StatusBadge>{dep.status}</StatusBadge></Link>)}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Certificate metadata</h2><p>Non-secret X.509 information</p></div></div><dl className="metadata"><dt>Common name</dt><dd>{cert.commonName}</dd><dt>Issuer</dt><dd>{cert.issuer}</dd><dt>Serial number</dt><dd className="mono">{cert.serialNumber}</dd><dt>Fingerprint</dt><dd className="mono">{cert.fingerprint}</dd><dt>Valid from</dt><dd>{formatDate(cert.notBefore)}</dd><dt>Renewal method</dt><dd>{cert.renewalMethod}</dd></dl></section>
      {workflow && <section className="panel span-2"><div className="panel-heading"><div><h2>Renewal workflow</h2><p>Deployment is progress. Successful validation is the finish line.</p></div><Link to={`${path('/renewals')}#${workflow.id}`}>Open renewal operations</Link></div><WorkflowTimeline workflow={workflow} tasks={tasks} compact /><div className="workflow-summary"><div><strong>{progressForTasks(tasks)}%</strong><span>task completion</span></div><div className="progress"><i style={{ width: `${progressForTasks(tasks)}%` }} /></div><span>Due {formatDate(workflow.dueDate)}</span></div><div className="task-list">{tasks.map((task) => <div className="task-row" key={task.id}><span className={`task-check ${task.status === 'Completed' ? 'done' : task.status === 'Failed' || task.status === 'Blocked' ? 'failed' : ''}`}>{task.status === 'Completed' ? <Check size={14} /> : task.status === 'Failed' || task.status === 'Blocked' ? <CircleAlert size={14} /> : <Clock3 size={14} />}</span><div className="grow"><strong>{task.title}</strong><span>{task.type} · {task.method} · {task.owner}</span>{task.vendor && <small>{task.vendor} · Ticket {task.ticketNumber}</small>}{task.deploymentId && <Link className="task-target-link" to={path(`/deployments/${task.deploymentId}`)}>Open deployment target</Link>}</div><StatusBadge>{task.type === 'Validation' && task.validationResult ? `${task.status} · ${task.validationResult}` : task.status}</StatusBadge>{task.status !== 'Completed' && task.status !== 'Blocked' && <button className="button tiny" onClick={() => void data.completeTask(task.id)}>Mark complete</button>}</div>)}</div></section>}
      <section className="panel span-2"><div className="panel-heading"><div><h2>Operational relationships</h2><p>One certificate connected to accountable deployment and validation work</p></div></div><div className="relationship-strip"><Link to={customer ? path(`/customers/${customer.id}`) : path('/customers')}><span>Customer</span><strong>{customer?.name ?? 'Unassigned'}</strong></Link><div><span>Environment</span><strong>{cert.environment}</strong></div><Link to={path('/deployments')}><span>Deployment targets</span><strong>{deployments.length} systems</strong></Link><Link to={path('/renewals')}><span>Renewal</span><strong>{workflow?.status ?? 'Not started'}</strong></Link><Link to={path('/runbooks')}><span>Runbooks</span><strong>{data.runbooks.filter((runbook) => deployments.some((deployment) => deployment.id === runbook.deploymentId)).length} associated</strong></Link><Link to={path('/activity')}><span>Evidence</span><strong>{validations.length} validations · {events.length} events</strong></Link></div></section>
      <section className="panel"><div className="panel-heading"><div><h2>Runbook</h2><p>Target-specific operating procedures</p></div></div>{data.runbooks.filter((runbook) => deployments.some((d) => d.id === runbook.deploymentId)).slice(0, 2).map((runbook) => <Link to={path('/runbooks')} className="runbook-link" key={runbook.id}><div><strong>{runbook.title}</strong><span>{runbook.steps.length} ordered steps</span></div><ExternalLink size={15} /></Link>)}</section>
      <section className="panel span-2"><div className="panel-heading"><div><h2>Validation</h2><p>Expected and observed deployment state</p></div></div>{validations.length ? validations.map((validation) => <div className="validation-row" key={validation.id}><div className={validation.success ? 'validation-icon success' : 'validation-icon failure'}>{validation.success ? <Check size={17} /> : <CircleAlert size={17} />}</div><div className="grow"><strong>{validation.type} · {validation.success ? 'Passed' : 'Failed'}</strong><span>Expected: {validation.expected}</span><small>Actual: {validation.actual}</small></div><time>{formatDate(validation.checkedAt)}</time></div>) : <p className="muted">No validation checks have been recorded.</p>}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Activity</h2><p>Append-oriented audit history</p></div></div>{events.length ? events.map((event) => <div className="mini-event" key={event.id}><span /><div><strong>{event.action.replaceAll('.', ' ')}</strong><p>{event.metadata}</p><small>{event.actor} · {formatDate(event.timestamp)}</small></div></div>) : <p className="muted">No activity recorded.</p>}</section>
    </div>{editing && <EditCertificate certificate={cert} onClose={() => setEditing(false)} />}</>
}

function EditCertificate({ certificate, onClose }: { certificate: NonNullable<ReturnType<typeof useData>['certificates'][number]>; onClose(): void }) { const data = useData(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const expiresAt = new Date(String(form.get('expiresAt'))); setBusy(true); setError(''); try { await data.updateCertificate(certificate.id, { commonName: String(form.get('commonName')).trim(), sanNames: String(form.get('sans')).split(',').map((value) => value.trim()).filter(Boolean), issuer: String(form.get('issuer')).trim(), expiresAt: expiresAt.toISOString(), notes: String(form.get('notes')).trim() }); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to update certificate.') } finally { setBusy(false) } } return <Modal title="Edit certificate metadata" onClose={onClose}><form className="form-grid" onSubmit={submit}><div className="form-note">Only non-secret certificate metadata is stored.</div><label className="full">Common name<input name="commonName" required defaultValue={certificate.commonName} /></label><label className="full">Subject alternative names<input name="sans" defaultValue={certificate.sanNames.join(', ')} /></label><label>Issuer<input name="issuer" required defaultValue={certificate.issuer} /></label><label>Expiration<input name="expiresAt" type="datetime-local" required defaultValue={certificate.expiresAt.slice(0, 16)} /></label><label className="full">Notes<textarea name="notes" rows={4} defaultValue={certificate.notes} /></label>{error && <p className="form-error full">{error}</p>}<div className="form-actions full"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : 'Save changes'}</button></div></form></Modal> }
