import { ChevronDown, ListFilter, Plus, Search } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { certificateStatus, daysUntil, formatDate } from '../lib/domain'
import type { Certificate } from '../types'

export function Certificates() {
  const data = useData(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All statuses'); const [customer, setCustomer] = useState('All customers'); const [showAdd, setShowAdd] = useState(false)
  const items = useMemo(() => data.certificates.filter((cert) => (cert.commonName.toLowerCase().includes(query.toLowerCase()) || cert.sanNames.some((san) => san.includes(query.toLowerCase()))) && (status === 'All statuses' || certificateStatus(cert) === status) && (customer === 'All customers' || cert.customerId === customer)).sort((a, b) => daysUntil(a.expiresAt) - daysUntil(b.expiresAt)), [data.certificates, query, status, customer])
  return <><PageHeader eyebrow="Certificate operations" title="Certificate inventory" description={`${data.certificates.length} certificates monitored across ${data.customers.length} customers.`} actions={<button className="button primary" onClick={() => setShowAdd(true)}><Plus size={16} /> Add certificate</button>} />
    <div className="toolbar"><label className="search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search common name or SAN…" /></label><label className="select"><ListFilter size={16} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option>All statuses</option>{['Healthy', 'Expiring Soon', 'Critical', 'Expired', 'Renewal In Progress', 'Validation Failed'].map((s) => <option key={s}>{s}</option>)}</select><ChevronDown size={14} /></label><label className="select"><select value={customer} onChange={(e) => setCustomer(e.target.value)}><option>All customers</option>{data.customers.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select><ChevronDown size={14} /></label><span className="result-count">{items.length} results</span></div>
    <div className="table-card"><div className="data-table cert-table"><div className="table-head"><span>Certificate</span><span>Customer / environment</span><span>Issuer</span><span>Expiration</span><span>Owner</span><span>Targets</span><span>Status</span></div>{items.map((cert) => <Link className="table-row" to={`/certificates/${cert.id}`} key={cert.id}><span className="primary-cell"><strong>{cert.commonName}</strong><small>{cert.sanNames.length} SAN{cert.sanNames.length === 1 ? '' : 's'} · {cert.renewalMethod}</small></span><span><strong>{data.customers.find((c) => c.id === cert.customerId)?.name}</strong><small>{cert.environment}</small></span><span><strong>{cert.certificateAuthority}</strong><small>{cert.issuer.slice(0, 30)}</small></span><span><strong className={daysUntil(cert.expiresAt) <= 7 ? 'text-danger' : ''}>{daysUntil(cert.expiresAt)} days</strong><small>{formatDate(cert.expiresAt)}</small></span><span><strong>{cert.owner}</strong><small>{cert.ownerTeam}</small></span><span><strong>{data.deployments.filter((d) => d.certificateId === cert.id).length}</strong></span><span><StatusBadge>{certificateStatus(cert)}</StatusBadge></span></Link>)}</div></div>
    {showAdd && <AddCertificate onClose={() => setShowAdd(false)} />}</>
}

function AddCertificate({ onClose }: { onClose(): void }) {
  const data = useData(); const [error, setError] = useState('')
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const expiresAt = new Date(String(form.get('expiresAt'))); if (Number.isNaN(expiresAt.getTime())) { setError('Enter a valid expiration date.'); return } const certificate: Certificate = { id: crypto.randomUUID(), customerId: String(form.get('customerId')), environment: String(form.get('environment')), commonName: String(form.get('commonName')).trim(), sanNames: String(form.get('sans')).split(',').map((s) => s.trim()).filter(Boolean), serialNumber: String(form.get('serial')), issuer: String(form.get('issuer')), certificateAuthority: String(form.get('authority')), notBefore: new Date().toISOString(), expiresAt: expiresAt.toISOString(), fingerprint: String(form.get('fingerprint')), renewalMethod: String(form.get('renewalMethod')), owner: 'Alex Morgan', ownerTeam: 'Certificate Operations', notes: String(form.get('notes')) }; if (!certificate.commonName || !certificate.customerId) { setError('Common name and customer are required.'); return } data.addCertificate(certificate); onClose() }
  return <Modal title="Add certificate metadata" onClose={onClose}><form className="form-grid" onSubmit={submit}><div className="form-note">Atlas stores certificate metadata only. Never paste or upload private key material.</div><label className="full">Common name<input name="commonName" required placeholder="api.example.com" /></label><label>Customer<select name="customerId" required>{data.customers.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Environment<input name="environment" required defaultValue="Production" /></label><label className="full">Subject alternative names<input name="sans" placeholder="api.example.com, www.example.com" /></label><label>Issuer<input name="issuer" required placeholder="DigiCert…" /></label><label>Certificate authority<input name="authority" required placeholder="DigiCert" /></label><label>Expiration date<input name="expiresAt" type="datetime-local" required /></label><label>Renewal method<input name="renewalMethod" required defaultValue="Manual" /></label><label>Serial number<input name="serial" /></label><label>Fingerprint<input name="fingerprint" /></label><label className="full">Notes<textarea name="notes" rows={3} /></label>{error && <p className="form-error full">{error}</p>}<div className="form-actions full"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Add metadata</button></div></form></Modal>
}
