import { ArrowRight, Building2, Plus } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState } from '../components/EmptyState'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { certificateStatus, daysUntil } from '../lib/domain'
import { useAppPath } from '../lib/routes'

export function Customers() { const data = useData(); const { path } = useAppPath(); const [showAdd, setShowAdd] = useState(false); return <><PageHeader eyebrow="Managed estate" title="Customers" description="Tenant-scoped certificate operations across every managed customer." actions={<button className="button primary" onClick={() => setShowAdd(true)}><Plus size={16} /> Add customer</button>} />{data.customers.length === 0 ? <EmptyState title="No customers created" description="Create the first managed customer, then add environments and certificate metadata." /> : <div className="customer-grid">{data.customers.map((customer) => { const certs = data.certificates.filter((certificate) => certificate.customerId === customer.id); const deployments = data.deployments.filter((deployment) => certs.some((certificate) => certificate.id === deployment.certificateId)); const workflows = data.workflows.filter((workflow) => certs.some((certificate) => certificate.id === workflow.certificateId)); const attention = certs.filter((certificate) => daysUntil(certificate.expiresAt) <= 30 || ['Validation Failed', 'Renewal In Progress'].includes(certificateStatus(certificate))); return <Link to={path(`/customers/${customer.id}`)} className="customer-card" key={customer.id}><div className="customer-top"><div className="customer-icon"><Building2 /></div><StatusBadge>{attention.length ? `${attention.length} Need Attention` : 'Healthy'}</StatusBadge></div><h2>{customer.name}</h2><p>{customer.industry}</p><div className="customer-metrics"><div><strong>{certs.length}</strong><span>Certificates</span></div><div><strong>{deployments.length}</strong><span>Targets</span></div><div><strong>{workflows.filter((workflow) => workflow.status !== 'Completed').length}</strong><span>Active renewals</span></div></div><div className="customer-footer"><span>{customer.environments.join(' · ') || 'No environments'}</span><ArrowRight size={16} /></div></Link> })}</div>}{showAdd && <AddCustomer onClose={() => setShowAdd(false)} />}</> }

function AddCustomer({ onClose }: { onClose(): void }) { const data = useData(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); try { await data.addCustomer({ name: String(form.get('name')).trim(), industry: String(form.get('industry')).trim() }); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create customer.') } finally { setBusy(false) } } return <Modal title="Add managed customer" onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="full">Customer name<input name="name" required minLength={2} maxLength={120} /></label><label className="full">Industry<input name="industry" maxLength={120} /></label>{error && <p className="form-error full">{error}</p>}<div className="form-actions full"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Creating…' : 'Create customer'}</button></div></form></Modal> }

export function CustomerDetail() { const data = useData(); const { id } = useParams(); const { path } = useAppPath(); const [showEnvironment, setShowEnvironment] = useState(false); const customer = data.customers.find((item) => item.id === id); if (!customer) return <EmptyState title="Customer not found" description="This customer may have been removed or is outside your organization." />; const certs = data.certificates.filter((certificate) => certificate.customerId === id); const deployments = data.deployments.filter((deployment) => certs.some((certificate) => certificate.id === deployment.certificateId)); return <><PageHeader eyebrow="Customer estate" title={customer.name} description={`${customer.industry || 'Industry not set'} · ${customer.environments.length} environments`} actions={<button className="button primary" onClick={() => setShowEnvironment(true)}><Plus size={16} /> Add environment</button>} /><div className="metric-grid compact"><div className="metric"><strong>{certs.length}</strong><h3>Certificates</h3></div><div className="metric warning"><strong>{certs.filter((certificate) => daysUntil(certificate.expiresAt) <= 30).length}</strong><h3>Expiring soon</h3></div><div className="metric"><strong>{deployments.length}</strong><h3>Deployment targets</h3></div><div className="metric critical"><strong>{data.validations.filter((validation) => !validation.success && certs.some((certificate) => certificate.id === validation.certificateId)).length}</strong><h3>Failed validations</h3></div></div><section className="panel"><div className="panel-heading"><div><h2>Certificate estate</h2><p>All monitored customer certificates</p></div></div>{certs.length === 0 ? <EmptyState title="No certificates" description="Add certificate metadata from the inventory to begin monitoring this customer." /> : certs.map((certificate) => <Link to={path(`/certificates/${certificate.id}`)} className="simple-row" key={certificate.id}><div className="grow"><strong>{certificate.commonName}</strong><span>{certificate.environment} · {daysUntil(certificate.expiresAt)} days remaining</span></div><StatusBadge>{certificateStatus(certificate)}</StatusBadge><ArrowRight size={15} /></Link>)}</section><section className="panel"><div className="panel-heading"><div><h2>Deployment targets</h2><p>Systems using certificates in this customer estate</p></div></div>{deployments.length === 0 ? <p className="muted">No deployment targets are associated with this customer.</p> : deployments.map((deployment) => <Link to={path(`/deployments/${deployment.id}`)} className="simple-row" key={deployment.id}><div className="grow"><strong>{deployment.name}</strong><span>{deployment.type} · {deployment.environment} · {deployment.hostname}</span></div><StatusBadge>{deployment.status}</StatusBadge><ArrowRight size={15} /></Link>)}</section>{showEnvironment && <AddEnvironment customerId={customer.id} onClose={() => setShowEnvironment(false)} />}</> }

function AddEnvironment({ customerId, onClose }: { customerId: string; onClose(): void }) { const data = useData(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { await data.addEnvironment({ customerId, name: String(form.get('name')).trim(), kind: String(form.get('kind')) }); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create environment.') } finally { setBusy(false) } } return <Modal title="Add customer environment" onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="full">Environment name<input name="name" required maxLength={80} placeholder="Production" /></label><label className="full">Type<select name="kind"><option value="production">Production</option><option value="staging">Staging</option><option value="development">Development</option><option value="custom">Custom</option></select></label>{error && <p className="form-error full">{error}</p>}<div className="form-actions full"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Adding…' : 'Add environment'}</button></div></form></Modal> }
