import { ArrowRight, Building2, Plus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { certificateStatus, daysUntil } from '../lib/domain'

export function Customers() { const data = useData(); return <><PageHeader eyebrow="Managed estate" title="Customers" description="Tenant-scoped certificate operations across every managed customer." actions={<button className="button primary"><Plus size={16} /> Add customer</button>} /><div className="customer-grid">{data.customers.map((customer) => { const certs = data.certificates.filter((c) => c.customerId === customer.id); const deps = data.deployments.filter((d) => certs.some((c) => c.id === d.certificateId)); const workflows = data.workflows.filter((w) => certs.some((c) => c.id === w.certificateId)); const attention = certs.filter((c) => daysUntil(c.expiresAt) <= 30 || ['Validation Failed', 'Renewal In Progress'].includes(certificateStatus(c))); return <Link to={`/customers/${customer.id}`} className="customer-card" key={customer.id}><div className="customer-top"><div className="customer-icon"><Building2 /></div><StatusBadge>{attention.length ? `${attention.length} Need Attention` : 'Healthy'}</StatusBadge></div><h2>{customer.name}</h2><p>{customer.industry}</p><div className="customer-metrics"><div><strong>{certs.length}</strong><span>Certificates</span></div><div><strong>{deps.length}</strong><span>Targets</span></div><div><strong>{workflows.filter((w) => w.status !== 'Completed').length}</strong><span>Active renewals</span></div></div><div className="customer-footer"><span>{customer.environments.join(' · ')}</span><ArrowRight size={16} /></div></Link> })}</div></> }

export function CustomerDetail() { const data = useData(); const id = location.pathname.split('/').pop(); const customer = data.customers.find((c) => c.id === id); if (!customer) return <p>Customer not found.</p>; const certs = data.certificates.filter((c) => c.customerId === id); const deps = data.deployments.filter((d) => certs.some((c) => c.id === d.certificateId)); return <><PageHeader eyebrow="Customer estate" title={customer.name} description={`${customer.industry} · ${customer.environments.length} environments`} /><div className="metric-grid compact"><div className="metric"><strong>{certs.length}</strong><h3>Certificates</h3></div><div className="metric warning"><strong>{certs.filter((c) => daysUntil(c.expiresAt) <= 30).length}</strong><h3>Expiring soon</h3></div><div className="metric"><strong>{deps.length}</strong><h3>Deployment targets</h3></div><div className="metric critical"><strong>{data.validations.filter((v) => !v.success && certs.some((c) => c.id === v.certificateId)).length}</strong><h3>Failed validations</h3></div></div><section className="panel"><div className="panel-heading"><div><h2>Certificate estate</h2><p>All monitored customer certificates</p></div></div>{certs.map((cert) => <Link to={`/certificates/${cert.id}`} className="simple-row" key={cert.id}><div className="grow"><strong>{cert.commonName}</strong><span>{cert.environment} · {daysUntil(cert.expiresAt)} days remaining</span></div><StatusBadge>{certificateStatus(cert)}</StatusBadge><ArrowRight size={15} /></Link>)}</section></> }
