import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, Globe2, KeyRound, RefreshCw, ShieldAlert, TimerOff, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { certificateStatus, daysUntil, formatDate, progressForTasks } from '../lib/domain'
import { useAppPath } from '../lib/routes'

export function Dashboard() {
  const data = useData()
  const { path } = useAppPath()
  const count = (status: string) => data.certificates.filter((cert) => certificateStatus(cert) === status).length
  const active = data.workflows.filter((workflow) => !['Completed'].includes(workflow.status))
  const vendorBlocked = data.tasks.filter((task) => task.type === 'Vendor Handoff' && task.status === 'Blocked')
  const needsAttention = data.certificates.filter((cert) => ['Critical', 'Expired', 'Validation Failed'].includes(certificateStatus(cert))).sort((a, b) => daysUntil(a.expiresAt) - daysUntil(b.expiresAt))
  return <>
    <PageHeader eyebrow="Operations overview" title="Good morning, Alex." description="Here’s what can expire or break next across your managed estate." actions={<><button className="button secondary">Export report</button><Link className="button primary" to={path('/certificates')}>Add certificate</Link></>} />
    {data.mode === 'demo' && <LiveCertificatePanel />}
    <section className="metric-grid">
      <Metric tag={data.mode === 'demo' ? 'DEMO' : 'LIVE'} icon={<KeyRound />} label="Certificates monitored" value={data.certificates.length} sub="Across 3 customers" />
      <Metric tag={data.mode === 'demo' ? 'DEMO' : 'LIVE'} icon={<Clock3 />} label="Expiring within 30 days" value={data.certificates.filter((cert) => { const days = daysUntil(cert.expiresAt); return days >= 0 && days <= 30 }).length} sub="Requires planning" tone="warning" />
      <Metric tag={data.mode === 'demo' ? 'DEMO' : 'LIVE'} icon={<ShieldAlert />} label="Critical within 7 days" value={count('Critical') + count('Renewal In Progress')} sub="Immediate action" tone="critical" />
      <Metric tag={data.mode === 'demo' ? 'DEMO' : 'LIVE'} icon={<TimerOff />} label="Expired" value={count('Expired') + count('Validation Failed')} sub="Service risk" tone="critical" />
      <Metric tag={data.mode === 'demo' ? 'DEMO' : 'LIVE'} icon={<Users />} label="Vendor blocked" value={vendorBlocked.length} sub="External dependency" tone="warning" />
      <Metric tag={data.mode === 'demo' ? 'DEMO' : 'LIVE'} icon={<AlertTriangle />} label="Failed validations" value={data.validations.filter((v) => !v.success).length} sub="Deployment incomplete" tone="critical" />
    </section>
    <div className="dashboard-grid">
      <section className="panel span-2"><div className="panel-heading"><div><h2>Needs attention</h2><p>Ordered by operational risk</p></div><Link to={path('/certificates')}>View inventory <ArrowRight size={14} /></Link></div><div className="attention-list">{needsAttention.map((cert) => { const customer = data.customers.find((item) => item.id === cert.customerId); return <Link className="attention-item" to={path(`/certificates/${cert.id}`)} key={cert.id}><div className="severity-icon"><AlertTriangle size={17} /></div><div className="grow"><strong>{cert.commonName}</strong><span>{customer?.name} · {cert.environment}</span></div><div className="expiry"><strong>{daysUntil(cert.expiresAt)}d</strong><span>{formatDate(cert.expiresAt)}</span></div><StatusBadge>{certificateStatus(cert)}</StatusBadge><ArrowRight size={15} /></Link> })}</div></section>
      <section className="panel"><div className="panel-heading"><div><h2>Vendor blocked</h2><p>Waiting on external parties</p></div></div>{vendorBlocked.map((task) => <div className="vendor-card" key={task.id}><div><StatusBadge>{task.status}</StatusBadge><span className="ticket">{task.ticketNumber}</span></div><h3>{task.title}</h3><p>{task.vendor}</p><div className="vendor-footer"><span>Due {formatDate(task.dueDate)}</span><Link to={path('/renewals')}>Open task</Link></div></div>)}</section>
      <section className="panel span-2"><div className="panel-heading"><div><h2>Renewals in progress</h2><p>Deployment completion by workflow</p></div><Link to={path('/renewals')}>Open queue <ArrowRight size={14} /></Link></div><div className="workflow-list">{active.map((workflow) => { const cert = data.certificates.find((item) => item.id === workflow.certificateId)!; const tasks = data.tasks.filter((task) => task.workflowId === workflow.id); const progress = progressForTasks(tasks); return <Link to={path(`/certificates/${cert.id}`)} className="workflow-row" key={workflow.id}><div className="grow"><strong>{cert.commonName}</strong><span>{data.customers.find((c) => c.id === cert.customerId)?.name} · Owner {workflow.owner}</span></div><StatusBadge>{workflow.status}</StatusBadge><div className="progress-wrap"><div><span>{tasks.filter((t) => t.status === 'Completed').length}/{tasks.length} tasks</span><strong>{progress}%</strong></div><div className="progress"><i style={{ width: `${progress}%` }} /></div></div></Link> })}</div></section>
      <section className="panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Latest operational changes</p></div><Link to={path('/activity')}>View all</Link></div><div className="timeline">{data.auditEvents.slice(0, 4).map((event) => <div key={event.id}><span className={event.action.includes('failed') ? 'event-dot danger' : 'event-dot'}>{event.action.includes('completed') ? <CheckCircle2 size={12} /> : ''}</span><p><strong>{event.action.replaceAll('.', ' ')}</strong>{event.metadata}</p><time>{formatDate(event.timestamp)}</time></div>)}</div></section>
    </div>
  </>
}

function LiveCertificatePanel() { const data = useData(); const refreshing = data.liveCertificateStatus === 'refreshing'; const cached = data.liveCertificateStatus === 'cached'; return <section className="live-certificate-panel"><div className="live-certificate-heading"><div><span className="source-label live"><Globe2 size={12} /> LIVE PUBLIC DATA</span><h2>Live certificate metadata</h2><p>Read-only TLS metadata from curated public endpoints. Operational relationships elsewhere in this workspace are fictional demonstration data.</p></div><div className="live-actions"><span>{data.liveCertificatesRefreshedAt ? `${cached ? 'Cached' : 'Checked'} ${new Date(data.liveCertificatesRefreshedAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}` : refreshing ? 'Connecting securely…' : 'Not yet checked'}</span><button className="button secondary" onClick={() => void data.refreshLiveCertificates(true)} disabled={refreshing}><RefreshCw size={14} className={refreshing ? 'spin' : ''} />{refreshing ? 'Refreshing…' : 'Refresh live certificates'}</button></div></div>{data.liveCertificateError && <div className="live-inspection-error"><AlertTriangle size={14} />{data.liveCertificateError}{cached && ' Showing the last successful browser cache.'}</div>}{data.liveCertificates.length > 0 ? <div className="live-certificate-grid">{data.liveCertificates.map((certificate) => <article key={certificate.hostname}><div><span className="live-pulse" /><strong>{certificate.hostname}</strong><small>{certificate.tlsProtocol}</small></div><h3>{certificate.commonName}</h3><dl><div><dt>Issuer</dt><dd>{certificate.issuer || 'Not reported'}</dd></div><div><dt>Expires</dt><dd>{formatDate(certificate.expiresAt)} · {daysUntil(certificate.expiresAt)}d</dd></div><div><dt>SANs</dt><dd>{certificate.sanNames.length}</dd></div><div><dt>Fingerprint</dt><dd className="mono">{certificate.fingerprint.slice(0, 20)}…</dd></div></dl></article>)}</div> : <div className="live-certificate-empty"><Globe2 size={20} /><div><strong>{refreshing ? 'Inspecting curated endpoints' : 'Live inspection temporarily unavailable'}</strong><span>The simulated operations workspace remains fully available.</span></div></div>}</section> }

function Metric({ icon, label, value, sub, tone = '', tag }: { icon: React.ReactNode; label: string; value: number; sub: string; tone?: string; tag: string }) { return <div className={`metric ${tone}`}><div className="metric-top"><span>{icon}</span><small>{tag}</small></div><strong>{value}</strong><h3>{label}</h3><p>{sub}</p></div> }
