import { ShieldCheck } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

function AuthFrame({ children }: { children: React.ReactNode }) { return <main className="login-page"><div className="login-brand"><div className="brand-mark"><ShieldCheck /></div><strong>Atlas CertOps</strong></div>{children}<Link className="demo-auth-link" to="/demo">Explore the demo workspace</Link></main> }
export function Login() { const auth = useAuth(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); if (auth.user && !auth.membershipLoading) return <Navigate to={auth.membership ? '/app' : '/onboarding'} replace />; async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { await auth.signIn(String(form.get('email')), String(form.get('password'))) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to sign in.') } finally { setBusy(false) } } return <AuthFrame><form className="login-card" onSubmit={submit}><span className="eyebrow">Secure workspace</span><h1>Sign in to Atlas</h1><p>Access your organization’s persistent certificate operations.</p>{auth.configurationError && <p className="form-error">{auth.configurationError}</p>}<label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" autoComplete="current-password" required minLength={8} /></label>{error && <p className="form-error">{error}</p>}<button className="button primary" disabled={busy || Boolean(auth.configurationError)}>{busy ? 'Signing in…' : 'Sign in'}</button><p className="auth-switch">New to Atlas? <Link to="/signup">Create a workspace</Link></p></form></AuthFrame> }

export function Signup() { const auth = useAuth(); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); if (auth.user && !auth.membershipLoading) return <Navigate to={auth.membership ? '/app' : '/onboarding'} replace />; async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { const result = await auth.signUp(String(form.get('email')), String(form.get('password')), String(form.get('fullName'))); if (result.confirmationRequired) setMessage('Check your email to confirm your account, then return to sign in.') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create account.') } finally { setBusy(false) } } return <AuthFrame><form className="login-card" onSubmit={submit}><span className="eyebrow">Start free</span><h1>Create your Atlas workspace</h1><p>Begin with an isolated organization and owner account.</p><label>Full name<input name="fullName" autoComplete="name" required /></label><label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" autoComplete="new-password" required minLength={8} /></label>{error && <p className="form-error">{error}</p>}{message && <p className="form-success">{message}</p>}<button className="button primary" disabled={busy || Boolean(auth.configurationError)}>{busy ? 'Creating account…' : 'Create account'}</button><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></form></AuthFrame> }

export function Onboarding() { const auth = useAuth(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); if (auth.loading || auth.membershipLoading) return <div className="app-loading">Checking organization membership…</div>; if (!auth.user) return <Navigate to="/login" replace />; if (auth.membership) return <Navigate to="/app" replace />; async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); try { await auth.bootstrapOrganization(String(new FormData(event.currentTarget).get('name'))) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create organization.') } finally { setBusy(false) } } return <AuthFrame><form className="login-card" onSubmit={submit}><span className="eyebrow">Organization setup</span><h1>Create your workspace</h1><p>This creates a new isolated organization and assigns you the Owner role.</p><label>Organization name<input name="name" required minLength={2} maxLength={100} placeholder="Acme Managed Services" /></label>{error && <p className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy ? 'Creating workspace…' : 'Create workspace'}</button><button type="button" className="button secondary" onClick={() => void auth.signOut()}>Sign out</button></form></AuthFrame> }
