import { BookOpen, CheckCircle2, ExternalLink, PlugZap, Plus, Search, ShieldCheck } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { formatDate } from '../lib/domain'

export function Deployments() { const data = useData(); return <><PageHeader eyebrow="Deployment estate" title="Deployment targets" description={`${data.deployments.length} known destinations across appliances, clusters, and external systems.`} actions={<button className="button primary"><Plus size={16} /> Add target</button>} /><div className="toolbar"><label className="search"><Search size={17} /><input placeholder="Search target or hostname…" /></label></div><div className="table-card"><div className="data-table deployment-table"><div className="table-head"><span>Target</span><span>Certificate</span><span>Method</span><span>Owner</span><span>Last deployment</span><span>Status</span></div>{data.deployments.map((dep) => <div className="table-row" key={dep.id}><span className="primary-cell"><strong>{dep.name}</strong><small>{dep.type} · {dep.hostname}</small></span><span><strong>{data.certificates.find((c) => c.id === dep.certificateId)?.commonName}</strong><small>{dep.environment}</small></span><span><strong>{dep.method}</strong><small>{dep.automationStatus}</small></span><span><strong>{dep.owner}</strong>{dep.vendor && <small>{dep.vendor}</small>}</span><span><strong>{dep.lastDeployment ? formatDate(dep.lastDeployment) : 'Never'}</strong><small>{dep.maintenanceWindow}</small></span><span><StatusBadge>{dep.status}</StatusBadge></span></div>)}</div></div></> }

export function Runbooks() { const data = useData(); return <><PageHeader eyebrow="Operating procedures" title="Runbooks" description="Repeatable, target-specific deployment knowledge for safe handoffs." actions={<button className="button primary"><Plus size={16} /> New runbook</button>} /><div className="runbook-grid">{data.runbooks.map((book) => <article className="runbook-card" key={book.id}><div className="runbook-icon"><BookOpen /></div><div><h2>{book.title}</h2><p>{book.description}</p></div><div className="runbook-meta"><span>{book.steps.length} steps</span><span>{book.warnings.length} warnings</span></div><ol>{book.steps.slice(0, 3).map((step) => <li key={step}>{step}</li>)}</ol><button className="button secondary">Open runbook <ExternalLink size={14} /></button></article>)}</div></> }

export function ActivityPage() { const data = useData(); return <><PageHeader eyebrow="Audit history" title="Operational activity" description="Append-oriented history of important lifecycle actions." actions={<button className="button secondary">Export audit log</button>} /><section className="panel"><div className="audit-list">{data.auditEvents.map((event) => <div className="audit-row" key={event.id}><span className={`audit-icon ${event.action.includes('failed') ? 'danger' : ''}`}><CheckCircle2 size={15} /></span><div className="grow"><strong>{event.action.replaceAll('.', ' ')}</strong><p>{event.metadata}</p><small>{event.entityType} · {event.entityId}</small></div><div><strong>{event.actor}</strong><time>{formatDate(event.timestamp)}</time></div></div>)}</div></section></> }

const integrations = [['DigiCert', 'Certificate metadata and renewal status', 'Planned'], ['AWS Certificate Manager', 'Inventory synchronization', 'Planned'], ['HashiCorp Vault', 'External secret reference only', 'Planned'], ['Kubernetes', 'Ingress discovery and deployment', 'Planned'], ['Slack', 'Operational notifications', 'Available soon'], ['Microsoft Teams', 'Operational notifications', 'Available soon']]
export function Integrations() { return <><PageHeader eyebrow="Extension points" title="Integrations" description="Connect the systems that issue, deploy, and observe certificates without moving private-key custody into Atlas." /><div className="integration-grid">{integrations.map(([name, description, status]) => <article className="integration-card" key={name}><div className="integration-icon"><PlugZap /></div><div className="grow"><h2>{name}</h2><p>{description}</p></div><StatusBadge>{status}</StatusBadge><button className="button secondary" disabled>Configure</button></article>)}</div><div className="security-callout"><ShieldCheck /><div><strong>Integration security boundary</strong><p>Atlas stores configuration metadata and external references. Provider credentials should use platform secrets; private keys remain in the customer’s approved system of record.</p></div></div></> }

export function SettingsPage() { return <><PageHeader eyebrow="Organization" title="Settings" description="Manage organization identity, access, lifecycle policy, and product limits." /><div className="settings-grid"><section className="panel"><h2>Organization profile</h2><label>Organization name<input defaultValue="Acme Managed Services" /></label><label>Default timezone<select defaultValue="America/Los_Angeles"><option>America/Los_Angeles</option><option>America/New_York</option><option>UTC</option></select></label><button className="button primary">Save changes</button></section><section className="panel"><h2>Expiration policy</h2><label>Expiring soon threshold<input type="number" defaultValue="30" /></label><label>Critical threshold<input type="number" defaultValue="7" /></label><p className="muted">Policy configuration is prepared in the database; demo thresholds remain fixed.</p><button className="button primary">Save policy</button></section><section className="panel"><h2>Plan usage</h2><div className="plan-label"><span>Team plan</span><strong>6 / 500 certificates</strong></div><div className="progress"><i style={{ width: '1.2%' }} /></div><p className="muted">Limits are centrally configurable and not embedded in feature logic.</p></section><section className="panel"><h2>Security posture</h2><ul className="check-list"><li><CheckCircle2 /> Row Level Security migration ready</li><li><CheckCircle2 /> Role-aware database policies</li><li><CheckCircle2 /> No private-key fields</li><li><CheckCircle2 /> Append-oriented audit events</li></ul></section></div></> }
