import { BookOpen, CheckCircle2, ExternalLink, PlugZap, Plus, Search, ShieldCheck } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { EmptyState } from '../components/EmptyState'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { formatDate } from '../lib/domain'

export function Deployments() { const data = useData(); const [showAdd, setShowAdd] = useState(false); return <><PageHeader eyebrow="Deployment estate" title="Deployment targets" description={`${data.deployments.length} known destinations across appliances, clusters, and external systems.`} actions={<button className="button primary" onClick={() => setShowAdd(true)} disabled={data.certificates.length === 0}><Plus size={16} /> Add target</button>} /><div className="toolbar"><label className="search"><Search size={17} /><input placeholder="Search target or hostname…" /></label></div>{data.deployments.length === 0 ? <EmptyState title="No deployment targets configured" description="Add a certificate first, then record every system where it is deployed." /> : <div className="table-card"><div className="data-table deployment-table"><div className="table-head"><span>Target</span><span>Certificate</span><span>Method</span><span>Owner</span><span>Last deployment</span><span>Status</span></div>{data.deployments.map((deployment) => <div className="table-row" key={deployment.id}><span className="primary-cell"><strong>{deployment.name}</strong><small>{deployment.type} · {deployment.hostname}</small></span><span><strong>{data.certificates.find((certificate) => certificate.id === deployment.certificateId)?.commonName}</strong><small>{deployment.environment}</small></span><span><strong>{deployment.method}</strong><small>{deployment.automationStatus}</small></span><span><strong>{deployment.owner}</strong>{deployment.vendor && <small>{deployment.vendor}</small>}</span><span><strong>{deployment.lastDeployment ? formatDate(deployment.lastDeployment) : 'Never'}</strong><small>{deployment.maintenanceWindow}</small></span><span><StatusBadge>{deployment.status}</StatusBadge></span></div>)}</div></div>}{showAdd && <AddDeployment onClose={() => setShowAdd(false)} />}</> }

function AddDeployment({ onClose }: { onClose(): void }) { const data = useData(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { await data.addDeployment({ certificateId: String(form.get('certificateId')), name: String(form.get('name')).trim(), type: String(form.get('type')), hostname: String(form.get('hostname')).trim(), method: String(form.get('method')), vendor: String(form.get('vendor')).trim(), maintenanceWindow: String(form.get('maintenanceWindow')).trim(), validationMethod: String(form.get('validationMethod')) }); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create deployment target.') } finally { setBusy(false) } } return <Modal title="Add deployment target" onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="full">Certificate<select name="certificateId" required>{data.certificates.map((certificate) => <option value={certificate.id} key={certificate.id}>{certificate.commonName} · {certificate.environment}</option>)}</select></label><label>Name<input name="name" required /></label><label>Target type<select name="type"><option>Nginx</option><option>F5</option><option>Citrix ADC</option><option>Palo Alto</option><option>Kubernetes ingress</option><option>Java keystore</option><option>Vendor-managed appliance</option><option>Other</option></select></label><label className="full">Hostname or reference<input name="hostname" required /></label><label>Deployment method<select name="method"><option value="manual">Manual</option><option value="automated">Automated</option><option value="vendor_assisted">Vendor Assisted</option><option value="external_system">External System</option></select></label><label>Validation method<select name="validationMethod"><option>Automatic TLS</option><option>Manual</option></select></label><label>Vendor<input name="vendor" /></label><label>Maintenance window<input name="maintenanceWindow" /></label>{error && <p className="form-error full">{error}</p>}<div className="form-actions full"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Adding…' : 'Add target'}</button></div></form></Modal> }

export function Runbooks() { const data = useData(); const [showAdd, setShowAdd] = useState(false); return <><PageHeader eyebrow="Operating procedures" title="Runbooks" description="Repeatable, target-specific deployment knowledge for safe handoffs." actions={<button className="button primary" onClick={() => setShowAdd(true)} disabled={data.deployments.length === 0}><Plus size={16} /> New runbook</button>} />{data.runbooks.length === 0 ? <EmptyState title="No runbooks" description="Add a deployment target, then capture its ordered replacement and validation procedure." /> : <div className="runbook-grid">{data.runbooks.map((book) => <article className="runbook-card" key={book.id}><div className="runbook-icon"><BookOpen /></div><div><h2>{book.title}</h2><p>{book.description}</p></div><div className="runbook-meta"><span>{book.steps.length} steps</span><span>{book.warnings.length} warnings</span></div><ol>{book.steps.slice(0, 3).map((step) => <li key={step}>{step}</li>)}</ol><button className="button secondary">Open runbook <ExternalLink size={14} /></button></article>)}</div>}{showAdd && <AddRunbook onClose={() => setShowAdd(false)} />}</> }

function AddRunbook({ onClose }: { onClose(): void }) { const data = useData(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { await data.addRunbook({ deploymentId: String(form.get('deploymentId')), title: String(form.get('title')).trim(), description: String(form.get('description')).trim(), steps: String(form.get('steps')).split('\n').map((value) => value.trim()).filter(Boolean), warnings: String(form.get('warnings')).split('\n').map((value) => value.trim()).filter(Boolean), expectedValidation: String(form.get('expectedValidation')).trim() }); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create runbook.') } finally { setBusy(false) } } return <Modal title="Create deployment runbook" onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="full">Deployment target<select name="deploymentId">{data.deployments.map((deployment) => <option value={deployment.id} key={deployment.id}>{deployment.name}</option>)}</select></label><label className="full">Title<input name="title" required /></label><label className="full">Description<textarea name="description" rows={2} /></label><label className="full">Ordered steps (one per line)<textarea name="steps" required rows={6} /></label><label className="full">Warnings (one per line)<textarea name="warnings" rows={3} /></label><label className="full">Expected validation<input name="expectedValidation" required /></label>{error && <p className="form-error full">{error}</p>}<div className="form-actions full"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Creating…' : 'Create runbook'}</button></div></form></Modal> }

export function ActivityPage() { const data = useData(); return <><PageHeader eyebrow="Audit history" title="Operational activity" description="Append-oriented history of important lifecycle actions." actions={<button className="button secondary">Export audit log</button>} />{data.auditEvents.length === 0 ? <EmptyState title="No activity recorded" description="Important production changes will appear here as append-only audit events." /> : <section className="panel"><div className="audit-list">{data.auditEvents.map((event) => <div className="audit-row" key={event.id}><span className={`audit-icon ${event.action.includes('failed') ? 'danger' : ''}`}><CheckCircle2 size={15} /></span><div className="grow"><strong>{event.action.replaceAll('.', ' ')}</strong><p>{event.metadata}</p><small>{event.entityType} · {event.entityId}</small></div><div><strong>{event.actor}</strong><time>{formatDate(event.timestamp)}</time></div></div>)}</div></section>}</> }

const integrations = [['DigiCert', 'Certificate metadata and renewal status', 'Planned'], ['AWS Certificate Manager', 'Inventory synchronization', 'Planned'], ['HashiCorp Vault', 'External secret reference only', 'Planned'], ['Kubernetes', 'Ingress discovery and deployment', 'Planned'], ['Slack', 'Operational notifications', 'Available soon'], ['Microsoft Teams', 'Operational notifications', 'Available soon']]
export function Integrations() { return <><PageHeader eyebrow="Extension points" title="Integrations" description="Connect the systems that issue, deploy, and observe certificates without moving private-key custody into Atlas." /><div className="integration-grid">{integrations.map(([name, description, status]) => <article className="integration-card" key={name}><div className="integration-icon"><PlugZap /></div><div className="grow"><h2>{name}</h2><p>{description}</p></div><StatusBadge>{status}</StatusBadge><button className="button secondary" disabled>Configure</button></article>)}</div><div className="security-callout"><ShieldCheck /><div><strong>Integration security boundary</strong><p>Atlas stores configuration metadata and external references. Provider credentials should use platform secrets; private keys remain in the customer’s approved system of record.</p></div></div></> }

export function SettingsPage() { const data = useData(); return <><PageHeader eyebrow="Organization" title="Settings" description="Manage organization identity, access, lifecycle policy, and product limits." /><div className="settings-grid"><section className="panel"><h2>Organization profile</h2><label>Organization name<input defaultValue={data.mode === 'demo' ? 'Acme Managed Services' : 'Production organization'} /></label><label>Default timezone<select defaultValue="America/Los_Angeles"><option>America/Los_Angeles</option><option>America/New_York</option><option>UTC</option></select></label><button className="button primary">Save changes</button></section><section className="panel"><h2>Expiration policy</h2><label>Expiring soon threshold<input type="number" defaultValue="30" /></label><label>Critical threshold<input type="number" defaultValue="7" /></label><p className="muted">Policy configuration is organization-scoped in PostgreSQL.</p><button className="button primary">Save policy</button></section><section className="panel"><h2>Plan usage</h2><div className="plan-label"><span>Team plan</span><strong>{data.certificates.length} / 500 certificates</strong></div><div className="progress"><i style={{ width: `${Math.min(100, data.certificates.length / 5)}%` }} /></div><p className="muted">Limits are centrally configurable and not embedded in feature logic.</p></section><section className="panel"><h2>Security posture</h2><ul className="check-list"><li><CheckCircle2 /> Row Level Security enabled</li><li><CheckCircle2 /> Role-aware database policies</li><li><CheckCircle2 /> No private-key fields</li><li><CheckCircle2 /> Append-oriented audit events</li></ul></section></div></> }
