import { AlertTriangle, Check, ChevronDown, Clock3, RotateCw } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { EmptyState } from '../components/EmptyState'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { daysUntil, formatDate, progressForTasks } from '../lib/domain'

export function Renewals() {
  const data = useData(); const [showStart, setShowStart] = useState(false); const workflows = [...data.workflows].sort((a, b) => daysUntil(a.dueDate) - daysUntil(b.dueDate))
  return <><PageHeader eyebrow="Lifecycle operations" title="Renewal queue" description="Coordinate issuance, deployment, handoffs, and post-deployment validation." actions={<button className="button primary" onClick={() => setShowStart(true)} disabled={data.certificates.length === 0} title={data.certificates.length === 0 ? 'Add a certificate before starting a renewal.' : undefined}><RotateCw size={16} /> Start renewal</button>} />
    <div className="queue-summary"><span><AlertTriangle /> Critical renewals <strong>{workflows.filter((w) => daysUntil(w.dueDate) <= 7 && w.status !== 'Completed').length}</strong></span><span><Clock3 /> Blocked tasks <strong>{data.tasks.filter((t) => t.status === 'Blocked').length}</strong></span><span><Check /> Recently completed <strong>{workflows.filter((w) => w.status === 'Completed').length}</strong></span></div>
    {workflows.length === 0 ? <EmptyState title="No renewals in progress" description="Start a renewal after adding a certificate and its deployment targets." /> : <div className="renewal-stack">{workflows.map((workflow) => { const cert = data.certificates.find((c) => c.id === workflow.certificateId)!; const customer = data.customers.find((c) => c.id === cert.customerId); const tasks = data.tasks.filter((task) => task.workflowId === workflow.id); const blocked = tasks.filter((t) => t.status === 'Blocked'); const progress = progressForTasks(tasks); return <details className="renewal-card" key={workflow.id} open><summary><div className="urgency"><strong>{daysUntil(cert.expiresAt)}</strong><span>days left</span></div><div className="grow"><h2>{cert.commonName}</h2><p>{customer?.name} · {cert.environment}</p><div className="tags"><StatusBadge>{workflow.status}</StatusBadge>{blocked.length > 0 && <StatusBadge>{`${blocked.length} Blocked`}</StatusBadge>}</div></div><div className="renewal-owner"><span>Owner</span><strong>{workflow.owner}</strong></div><div className="renewal-progress"><div><span>{tasks.filter((t) => t.status === 'Completed').length}/{tasks.length} complete</span><strong>{progress}%</strong></div><div className="progress"><i style={{ width: `${progress}%` }} /></div></div><ChevronDown /></summary><div className="expanded-tasks">{tasks.map((task) => <div className="task-row" key={task.id}><span className={`task-check ${task.status === 'Completed' ? 'done' : task.status === 'Failed' ? 'failed' : ''}`}>{task.status === 'Completed' ? <Check size={14} /> : <Clock3 size={14} />}</span><div className="grow"><strong>{task.title}</strong><span>{task.type} · Due {formatDate(task.dueDate)}</span>{task.vendor && <small>{task.vendor} · {task.ticketNumber}</small>}</div><StatusBadge>{task.status}</StatusBadge>{['Pending', 'In Progress'].includes(task.status) && <button className="button tiny" onClick={() => void data.completeTask(task.id)}>Mark complete</button>}{task.status === 'Failed' && <button className="button tiny" onClick={() => void data.retryTask(task.id)}>Retry</button>}</div>)}</div></details> })}</div>}{showStart && <StartRenewal onClose={() => setShowStart(false)} />}</>
}

function StartRenewal({ onClose }: { onClose(): void }) { const data = useData(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); try { await data.startRenewal(String(new FormData(event.currentTarget).get('certificateId'))); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to start renewal.') } finally { setBusy(false) } } return <Modal title="Start certificate renewal" onClose={onClose}><form className="form-grid" onSubmit={submit}><div className="form-note">Atlas will generate deployment and validation tasks from the certificate’s configured targets. It does not issue the certificate.</div><label className="full">Certificate<select name="certificateId" required>{data.certificates.map((certificate) => <option value={certificate.id} key={certificate.id}>{certificate.commonName} · {certificate.environment}</option>)}</select></label>{error && <p className="form-error full">{error}</p>}<div className="form-actions full"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Starting…' : 'Generate renewal tasks'}</button></div></form></Modal> }
