import { AlertTriangle, Check, ChevronDown, Clock3, RotateCw } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { useData } from '../context/DataContext'
import { daysUntil, formatDate, progressForTasks } from '../lib/domain'

export function Renewals() {
  const data = useData(); const workflows = [...data.workflows].sort((a, b) => daysUntil(a.dueDate) - daysUntil(b.dueDate))
  return <><PageHeader eyebrow="Lifecycle operations" title="Renewal queue" description="Coordinate issuance, deployment, handoffs, and post-deployment validation." actions={<button className="button primary"><RotateCw size={16} /> Start renewal</button>} />
    <div className="queue-summary"><span><AlertTriangle /> Critical renewals <strong>{workflows.filter((w) => daysUntil(w.dueDate) <= 7 && w.status !== 'Completed').length}</strong></span><span><Clock3 /> Blocked tasks <strong>{data.tasks.filter((t) => t.status === 'Blocked').length}</strong></span><span><Check /> Recently completed <strong>{workflows.filter((w) => w.status === 'Completed').length}</strong></span></div>
    <div className="renewal-stack">{workflows.map((workflow) => { const cert = data.certificates.find((c) => c.id === workflow.certificateId)!; const customer = data.customers.find((c) => c.id === cert.customerId); const tasks = data.tasks.filter((task) => task.workflowId === workflow.id); const blocked = tasks.filter((t) => t.status === 'Blocked'); const progress = progressForTasks(tasks); return <details className="renewal-card" key={workflow.id} open><summary><div className="urgency"><strong>{daysUntil(cert.expiresAt)}</strong><span>days left</span></div><div className="grow"><h2>{cert.commonName}</h2><p>{customer?.name} · {cert.environment}</p><div className="tags"><StatusBadge>{workflow.status}</StatusBadge>{blocked.length > 0 && <StatusBadge>{`${blocked.length} Blocked`}</StatusBadge>}</div></div><div className="renewal-owner"><span>Owner</span><strong>{workflow.owner}</strong></div><div className="renewal-progress"><div><span>{tasks.filter((t) => t.status === 'Completed').length}/{tasks.length} complete</span><strong>{progress}%</strong></div><div className="progress"><i style={{ width: `${progress}%` }} /></div></div><ChevronDown /></summary><div className="expanded-tasks">{tasks.map((task) => <div className="task-row" key={task.id}><span className={`task-check ${task.status === 'Completed' ? 'done' : task.status === 'Failed' ? 'failed' : ''}`}>{task.status === 'Completed' ? <Check size={14} /> : <Clock3 size={14} />}</span><div className="grow"><strong>{task.title}</strong><span>{task.type} · Due {formatDate(task.dueDate)}</span>{task.vendor && <small>{task.vendor} · {task.ticketNumber}</small>}</div><StatusBadge>{task.status}</StatusBadge>{['Pending', 'In Progress'].includes(task.status) && <button className="button tiny" onClick={() => data.completeTask(task.id)}>Mark complete</button>}{task.status === 'Failed' && <button className="button tiny" onClick={() => data.retryTask(task.id)}>Retry</button>}</div>)}</div></details> })}</div></>
}
